// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface LocalProviderRouter$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "LocalProviderRouter";
  readonly sourceName: "contracts/adapters/LocalProviderRouter.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"from","type":"address"},{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}],"name":"Accepted","type":"event"},{"stateMutability":"payable","type":"receive"}];
  readonly bytecode: "0x60808060405234601357606f908160188239f35b5f80fdfe6080806040523615600e575f80fd5b3481527fba19e87fb846feb0297591bc7d3f55ec0e3b289f88871a2bcfbe84d66fb47d4a60203392a200fea264697066735822122033fc146787c0c1accdf10f61bc9079391abef44969334b6e0508ca8966f9311e64736f6c63430008180033";
  readonly deployedBytecode: "0x6080806040523615600e575f80fd5b3481527fba19e87fb846feb0297591bc7d3f55ec0e3b289f88871a2bcfbe84d66fb47d4a60203392a200fea264697066735822122033fc146787c0c1accdf10f61bc9079391abef44969334b6e0508ca8966f9311e64736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/adapters/LocalProviderRouter.sol";
  readonly buildInfoId: "solc-0_8_24-be40f2614bbacbc8b5aa463053c330da5214a9dd";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["LocalProviderRouter"]: LocalProviderRouter$Type;
    ["contracts/adapters/LocalProviderRouter.sol:LocalProviderRouter"]: LocalProviderRouter$Type;
  }
}