server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /runtime-config.js {
    default_type application/javascript;
    alias /etc/nginx/runtime-config.js;
  }

  location /admin {
    alias /usr/share/nginx/html/admin;
    try_files $uri $uri/ /admin/index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
