// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IAggregatorAdapter$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IAggregatorAdapter";
  readonly sourceName: "contracts/executor/IAggregatorAdapter.sol";
  readonly abi: [{"inputs":[{"components":[{"internalType":"bytes32","name":"invoiceId","type":"bytes32"},{"internalType":"address","name":"token","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"},{"internalType":"uint256","name":"destChainId","type":"uint256"},{"internalType":"bytes","name":"destToken","type":"bytes"},{"internalType":"bytes","name":"recipient","type":"bytes"},{"internalType":"uint256","name":"minAmountOut","type":"uint256"},{"internalType":"address","name":"refundTo","type":"address"}],"internalType":"struct AdapterContext","name":"ctx","type":"tuple"},{"internalType":"bytes","name":"routeData","type":"bytes"}],"name":"execute","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[],"name":"executor","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"providerId","outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/executor/IAggregatorAdapter.sol";
  readonly buildInfoId: "solc-0_8_24-d20a968b3862a8df806565f7c58628c5fb9189bb";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IAggregatorAdapter"]: IAggregatorAdapter$Type;
    ["contracts/executor/IAggregatorAdapter.sol:IAggregatorAdapter"]: IAggregatorAdapter$Type;
  }
}