// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface InvoiceStackLinker$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "InvoiceStackLinker";
  readonly sourceName: "contracts/invoice-stack.sol";
  readonly abi: [];
  readonly bytecode: "0x608080604052346013576039908160188239f35b5f80fdfe5f80fdfea26469706673582212208fc97978e171acb56d82fd9f34e5aa29631df95a209daf3fa1e7dd3821dbc5b264736f6c63430008180033";
  readonly deployedBytecode: "0x5f80fdfea26469706673582212208fc97978e171acb56d82fd9f34e5aa29631df95a209daf3fa1e7dd3821dbc5b264736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/invoice-stack.sol";
  readonly buildInfoId: "solc-0_8_24-619306ef5e517fa08b2fa349135178c293c103b1";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["InvoiceStackLinker"]: InvoiceStackLinker$Type;
    ["contracts/invoice-stack.sol:InvoiceStackLinker"]: InvoiceStackLinker$Type;
  }
}